version: '3.1'
networks:
  api_networks:
# volumes:
#   dbdata6:
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27017:27017'
    # volumes:
    #   - dbdata6:/data/db
    restart: always
    env_file:
      - .env
    networks:
      - api_networks

  # app:
  #   build:
  #     context: ./
  #   container_name: app
  #   ports:
  #     - '8080:8080'
  #   networks:
  #     - api_networks
  #   env_file:
  #     - .env
  #   restart: always
  #   command: bash -c "cargo run"
  #   depends_on:
  #     - mongo    
