# version: '3.1'
# networks:
#   api_networks:
# # volumes:
# #   dbdata6:
# services:
#   mongo:
#     image: mongo:latest
#     container_name: mongo
#     ports:
#       - '27017:27017'
#     # volumes:
#     #   - dbdata6:/data/db
#     restart: always
#     env_file:
#       - .env
#     networks:
#       - api_networks
#   mongo-express:
#     image: mongo-express:latest
#     container_name: mongo-express
#     environment:
#       ME_CONFIG_MONGODB_ADMINUSERNAME: root
#       ME_CONFIG_MONGODB_ADMINPASSWORD: example
#       ME_CONFIG_MONGODB_SERVER: localhost
#       ME_CONFIG_MONGODB_PORT: "27017"
#       ME_CONFIG_MONGODB_URL: "mongodb://MONGO_INITDB_ROOT_USERNAME:example@localhost:27017/rust_mongodb?authSource=admin"
#     ports:
#       - "27010:27010"
#     networks:
#       - api_networks
#     depends_on:
#       - mongo

  # app:
  #   build:
  #     context: ./
  #   container_name: app
  #   ports:
  #     - '8080:8080'
  #   networks:
  #     - api_networks
  #   env_file:
  #     - .env
  #   restart: always
  #   command: bash -c "cargo run"
  #   depends_on:
  #     - mongo    


version: '3.1'
services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    env_file:
      - .env
    ports:
      - 27017:27017
  mongo_ui:
    image: mongo-express:latest
    restart: always
    container_name: mongo_ui
    depends_on:
      - mongo
    ports:
      - 8081:8081
    env_file:
      - .env
