version: '3.1'
services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    env_file:
      - .env
    ports:
      - 27017:27017
  mongo_ui:
    image: mongo-express:latest
    restart: always
    container_name: mongo_ui
    depends_on:
      - mongo
    ports:
      - 8081:8081
    env_file:
      - .env
